---
services: docker

script:
  - docker build -t ansible-tstimg .
  - docker run --name ansible-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ansible-tstimg /sbin/init
  - docker exec --tty ansible-container env TERM=xterm ansible --version
