---
services: docker

script:
  - docker build -t ansible-tstimg .
  - docker run --name ansible-tstimg -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ansible-tstimg /lib/systemd/systemd
  - docker exec --tty ansible-tstimg env TERM=xterm ansible --version
